# Generated by Django 5.1.4 on 2026-02-20 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0002_assessmentattempt_current_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.CharField(max_length=20)),
                ('overall_points', models.FloatField(default=0)),
                ('interests_snapshot', models.TextField(blank=True)),
                ('generated_by', models.CharField(default='LocalAI', max_length=50)),
                ('prompt_signature', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(default='v1', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_roadmaps', to='learning.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIRoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('est_time_hours', models.FloatField(default=1)),
                ('outcome', models.TextField()),
                ('resource_title', models.CharField(blank=True, max_length=255)),
                ('resource_url', models.URLField(blank=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='roadmaps.airoadmap')),
            ],
            options={
                'ordering': ['step_no'],
            },
        ),
    ]
