# Generated by Django 5.1.4 on 2026-02-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Student', 'Student'), ('Working', 'Working'), ('Unemployed', 'Unemployed'), ('Other', 'Other')], default='Student', max_length=20),
        ),
    ]
