# Generated by Django 5.1.4 on 2026-02-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackresponse',
            name='feedback_type',
            field=models.CharField(choices=[('PASS_FEEDBACK', 'PASS_FEEDBACK'), ('FAIL_DIFFICULTY', 'FAIL_DIFFICULTY')], default='PASS_FEEDBACK', max_length=20),
        ),
    ]
