# Generated by Django 5.1.4 on 2026-02-20 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='current_level',
            field=models.CharField(default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='selected_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_attempts', to='learning.course'),
        ),
    ]
